name: voyager
description: Local-first journaling and productivity app.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  uuid: ^4.5.1
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.5
  path: ^1.9.1
  fl_chart: ^0.70.2
  collection: ^1.19.1
  hotkey_manager: ^0.2.3
  intl: ^0.20.2
  http: ^1.4.0
  url_launcher: ^6.3.1
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  cloud_firestore: ^6.6.0
  cloud_functions: ^6.3.3
  phosphoricons_flutter: ^1.0.0
  oauth2: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.0

flutter:
  uses-material-design: true
  assets:
    - assets/quotes.json
  fonts:
    - family: IosevkaAile
      fonts:
        - asset: assets/Iosevka-Thin/Iosevka-Aile-Light-01.ttf
          weight: 300
        - asset: assets/Iosevka-Thin/Iosevka-Aile-Light-Italic-03.ttf
          weight: 300
          style: italic
        - asset: assets/Iosevka-Regular/Iosevka-Aile-01.ttf
          weight: 400
        - asset: assets/Iosevka-Regular/Iosevka-Aile-Italic-03.ttf
          weight: 400
          style: italic
        - asset: assets/Iosevka-Bold/Iosevka-Aile-Bold-01.ttf
          weight: 700
        - asset: assets/Iosevka-Bold/Iosevka-Aile-Bold-Italic-03.ttf
          weight: 700
          style: italic
