import 'package:voyager/domain/services/character_operation.dart';
import 'package:voyager/domain/services/fractional_index.dart';

/// Tracks in-memory character ops for an actively edited text field.
class CharacterOpSession {
  CharacterOpSession({
    required this.clientId,
    String? initialText,
    List<CharacterOperation>? initialOperations,
    /// When true, ops generated by seeding from [initialText] are added to
    /// [_pendingOpIds] so they will be uploaded as the initial CRDT chain for
    /// a brand-new document that has no remote ops yet.
    ///
    /// Keep this false (the default) when creating a session purely to
    /// reconstruct local state — e.g. from a race path where the user typed
    /// before [prepareEditingSession] finished loading the real remote chain.
    /// In that case only the actual edit delta should be uploaded, not a fresh
    /// copy of every existing character, which would collide with the positions
    /// already present in Firestore from the original authoring session.
    bool seedAsPending = false,
  }) : _logicalClock = 0 {
    if (initialOperations != null) {
      _loadFromOperations(initialOperations);
    } else if (initialText != null) {
      _seedFromText(initialText, markAsPending: seedAsPending);
    }
  }

  final String clientId;
  int _logicalClock;
  final Map<String, CharacterOperation> _opsById = {};
  final List<String> _pendingOpIds = [];

  List<CharacterOperation> get allOps =>
      _opsById.values.toList(growable: false);

  String get text => _reconstructText();

  /// The live operations in document order, and the text they spell.
  ///
  /// Cached because [recordTextChange] runs on every keystroke, and rebuilding
  /// the order means sorting every character by a position string that grows
  /// with the document — 15ms a keystroke at 8k characters, 200ms at 20k.
  /// [recordTextChange] keeps both up to date itself; everything else that
  /// changes [_opsById] wholesale clears them.
  List<CharacterOperation>? _live;
  String? _liveText;

  void resetFromText(String text) {
    _opsById.clear();
    _pendingOpIds.clear();
    _logicalClock = 0;
    _seedFromText(text, markAsPending: true);
  }

  void recordTextChange(String before, String after) {
    if (before == after) return;

    final live = _liveOrderedOps();
    // When the session already spells `before`, the edit below leaves it
    // spelling exactly `after`, so the rebuild the final check would do can be
    // skipped. Length too: the diff indexes ops by UTF-16 offset.
    final inSync = live.length == before.length && _reconstructText() == before;
    final oldText = before;

    // Simple diff: walk both strings.
    var i = 0;
    var j = 0;
    while (i < oldText.length && j < after.length && oldText[i] == after[j]) {
      i++;
      j++;
    }

    var oldEnd = oldText.length;
    var newEnd = after.length;
    while (oldEnd > i &&
        newEnd > j &&
        oldText[oldEnd - 1] == after[newEnd - 1]) {
      oldEnd--;
      newEnd--;
    }

    final deleteCount = oldEnd - i;
    final insertSegment = after.substring(j, newEnd);

    if (deleteCount > 0 && i < live.length) {
      final end = i + deleteCount < live.length ? i + deleteCount : live.length;
      for (final op in live.sublist(i, end)) {
        _tombstone(op.id);
      }
      live.removeRange(i, end);
    }

    if (insertSegment.isNotEmpty) {
      String? posBefore;
      String? posAfter;
      if (i > 0 && i - 1 < live.length) {
        posBefore = live[i - 1].position;
      }
      if (i < live.length) {
        posAfter = live[i].position;
        var nextIdx = i + 1;
        while (posAfter == posBefore && nextIdx < live.length) {
          posAfter = live[nextIdx].position;
          nextIdx++;
        }
        if (posAfter == posBefore) {
          posAfter = null;
        }
      }

      var cursorBefore = posBefore;
      final inserted = <CharacterOperation>[];
      for (var k = 0; k < insertSegment.length; k++) {
        final char = insertSegment[k];
        final pos = FractionalIndex.between(
          before: cursorBefore,
          after: posAfter,
        );
        inserted.add(_insertOp(char: char, position: pos));
        cursorBefore = pos;
      }

      // Spliced in at the diff index, which is where a sort would put them as
      // long as they sort strictly between their new neighbours. When they
      // don't — equal positions skipped above, or a desynced index — the
      // cached order is dropped and the next read sorts from scratch.
      if (i <= live.length) {
        live.insertAll(i, inserted);
        final next = i + inserted.length;
        if ((i > 0 &&
                live[i - 1].position.compareTo(inserted.first.position) >= 0) ||
            (next < live.length &&
                inserted.last.position.compareTo(live[next].position) >= 0)) {
          _live = null;
        }
      } else {
        _live = null;
      }
    }

    _liveText = inSync && _live != null ? after : null;

    // If diff produced no ops but text changed structurally, re-seed.
    if (_reconstructText() != after) {
      resetFromText(after);
    }
  }

  List<CharacterOperation> takePendingOps() {
    final pending = _pendingOpIds
        .map((id) => _opsById[id])
        .whereType<CharacterOperation>()
        .toList();
    _pendingOpIds.clear();
    return pending;
  }

  /// Puts operations from a failed upload back in the pending set.
  ///
  /// [takePendingOps] clears unconditionally, so an upload that then throws
  /// used to lose those operations for good: they stay in [_opsById], which
  /// means [text] already accounts for them and no later [recordTextChange]
  /// will ever emit them again. The paragraph typed offline would simply never
  /// reach `sync_operations`, and any device resolving the document from the
  /// log would render it missing.
  ///
  /// Restored at the front, because the user may have kept typing while the
  /// upload was in flight and those newer operations must still follow these.
  /// Ids already pending are left alone rather than duplicated — an operation
  /// tombstoned after it was taken is back in the list under its own id.
  void restorePendingOps(List<CharacterOperation> operations) {
    if (operations.isEmpty) return;
    final alreadyPending = _pendingOpIds.toSet();
    final restored = [
      for (final op in operations)
        if (_opsById.containsKey(op.id) && alreadyPending.add(op.id)) op.id,
    ];
    if (restored.isEmpty) return;
    _pendingOpIds.insertAll(0, restored);
  }

  void _seedFromText(String text, {bool markAsPending = false}) {
    _live = null;
    _liveText = null;
    final positions = FractionalIndex.spread(text.length);
    for (var i = 0; i < text.length; i++) {
      final char = text[i];
      final pos = positions[i];
      final id = '${clientId}_${_logicalClock}_$pos';
      _opsById[id] = CharacterOperation(
        id: id,
        clientId: clientId,
        logicalClock: _logicalClock++,
        position: pos,
        character: char,
      );
      if (markAsPending) _pendingOpIds.add(id);
    }
  }

  void _loadFromOperations(List<CharacterOperation> operations) {
    _live = null;
    _liveText = null;
    var maxClock = -1;
    for (final op in operations) {
      _opsById[op.id] = op;
      if (op.clientId == clientId && op.logicalClock > maxClock) {
        maxClock = op.logicalClock;
      }
    }
    _logicalClock = maxClock + 1;
  }

  CharacterOperation _insertOp({
    required String char,
    required String position,
  }) {
    final id = '${clientId}_${_logicalClock}_$position';
    final op = CharacterOperation(
      id: id,
      clientId: clientId,
      logicalClock: _logicalClock++,
      position: position,
      character: char,
    );
    _opsById[id] = op;
    _pendingOpIds.add(id);
    return op;
  }

  void _tombstone(String id) {
    final existing = _opsById[id];
    if (existing == null || existing.deleted) return;
    final tombstoned = existing.copyWith(deleted: true);
    _opsById[id] = tombstoned;
    _pendingOpIds.add(id);
  }

  List<CharacterOperation> _liveOrderedOps() {
    return _live ??= (_opsById.values.where((op) => !op.deleted).toList()
      ..sort((a, b) => a.position.compareTo(b.position)));
  }

  String _reconstructText() {
    return _liveText ??= _liveOrderedOps().map((op) => op.character).join();
  }
}

/// Registry of active character-op editing sessions keyed by document.
class CharacterOpRegistry {
  final Map<String, CharacterOpSession> _sessions = {};

  String key(String collection, String documentId) =>
      '${collection}_$documentId';

  CharacterOpSession ensureSession({
    required String collection,
    required String documentId,
    required String clientId,
    String? initialText,
    List<CharacterOperation>? operations,
    bool markSeedsAsPending = false,
  }) {
    final k = key(collection, documentId);
    return _sessions.putIfAbsent(
      k,
      () => CharacterOpSession(
        clientId: clientId,
        initialText: initialText,
        initialOperations: operations,
        seedAsPending: markSeedsAsPending,
      ),
    );
  }

  void loadSession({
    required String collection,
    required String documentId,
    required String clientId,
    required List<CharacterOperation> operations,
  }) {
    final k = key(collection, documentId);
    _sessions[k] = CharacterOpSession(
      clientId: clientId,
      initialOperations: operations,
    );
  }

  CharacterOpSession? session(String collection, String documentId) {
    return _sessions[key(collection, documentId)];
  }

  void recordTextChange({
    required String collection,
    required String documentId,
    required String clientId,
    required String before,
    required String after,
  }) {
    final session = ensureSession(
      collection: collection,
      documentId: documentId,
      clientId: clientId,
      initialText: before,
    );
    session.recordTextChange(before, after);
  }

  List<CharacterOperation> takePendingOps(String collection, String documentId) {
    return _sessions[key(collection, documentId)]?.takePendingOps() ??
        const [];
  }

  /// Returns operations to the pending set after their upload failed — see
  /// [CharacterOpSession.restorePendingOps].
  void restorePendingOps(
    String collection,
    String documentId,
    List<CharacterOperation> operations,
  ) {
    _sessions[key(collection, documentId)]?.restorePendingOps(operations);
  }

  void resetSession({
    required String collection,
    required String documentId,
    required String clientId,
    required String text,
  }) {
    final k = key(collection, documentId);
    _sessions[k] = CharacterOpSession(clientId: clientId, initialText: text);
  }

  void removeSession(String collection, String documentId) {
    _sessions.remove(key(collection, documentId));
  }

  void clear() => _sessions.clear();
}
