/// Stages seeded the first time the Jobs page is opened. Order here is the
/// initial display order; the user may rename, reorder and delete freely.
const jobSeedStages = <String>[
  'Applied',
  'Online Assessment',
  'Interview',
  'Accepted',
  'Rejected',
];

/// The stage a new application lands in: the first entry in the user's ordered
/// stage list, which starts out as [jobSeedStages]`.first`.
const jobDefaultStage = 'Applied';

/// Companies pre-loaded into the typeahead so the very first application has
/// something to complete against. Seeded once, then treated exactly like a
/// user-added entry — renameable, categorisable and deletable.
const jobSeedCompanies = <String>[
  'Adobe',
  'Airbnb',
  'Akuna Capital',
  'Amazon',
  'AMD',
  'American Express',
  'Anthropic',
  'Apple',
  'Applied Materials',
  'Arista Networks',
  'Asana',
  'Atlassian',
  'Bank of America',
  'Blackstone',
  'Bloomberg',
  'Boeing',
  'Booking.com',
  'Box',
  'Bridgewater Associates',
  'Broadcom',
  'ByteDance',
  'Capital One',
  'Cisco',
  'Citadel',
  'Citadel Securities',
  'Citi',
  'Cloudflare',
  'Coinbase',
  'Confluent',
  'Coupang',
  'Cruise',
  'Databricks',
  'Datadog',
  'Dell Technologies',
  'Deloitte',
  'DoorDash',
  'Dropbox',
  'DRW',
  'eBay',
  'Electronic Arts',
  'Epic Games',
  'Epic Systems',
  'Ernst & Young',
  'Etsy',
  'Expedia Group',
  'Figma',
  'Five Rings',
  'Ford',
  'GitHub',
  'GitLab',
  'Goldman Sachs',
  'Google',
  'Grammarly',
  'HashiCorp',
  'Hewlett Packard Enterprise',
  'HP',
  'HRT',
  'Hudson River Trading',
  'IBM',
  'Instacart',
  'Intel',
  'Intuit',
  'IMC Trading',
  'Jane Street',
  'Johnson & Johnson',
  'JPMorgan Chase',
  'Jump Trading',
  'KLA',
  'Klaviyo',
  'Lockheed Martin',
  'Lucid Motors',
  'Lyft',
  'Marvell',
  'Mastercard',
  'McKinsey & Company',
  'Meta',
  'Micron Technology',
  'Microsoft',
  'MongoDB',
  'Morgan Stanley',
  'Motional',
  'Netflix',
  'Nordstrom',
  'Northrop Grumman',
  'Notion',
  'Nubank',
  'Nvidia',
  'Okta',
  'OpenAI',
  'Optiver',
  'Oracle',
  'Palantir',
  'Palo Alto Networks',
  'PayPal',
  'Peloton',
  'Pinterest',
  'Plaid',
  'Point72',
  'PwC',
  'Qualcomm',
  'Quora',
  'Rakuten',
  'Ramp',
  'Reddit',
  'Riot Games',
  'Rippling',
  'Rivian',
  'Roblox',
  'Robinhood',
  'Roku',
  'Salesforce',
  'Samsung',
  'SAP',
  'Scale AI',
  'Snap',
  'Snowflake',
  'SoFi',
  'SpaceX',
  'Splunk',
  'Spotify',
  'Square',
  'Stripe',
  'Susquehanna International Group',
  'Tesla',
  'Texas Instruments',
  'The Trade Desk',
  'TikTok',
  'Toast',
  'Tower Research Capital',
  'Twilio',
  'Two Sigma',
  'Uber',
  'UiPath',
  'Unity',
  'Verkada',
  'Visa',
  'VMware',
  'Waymo',
  'Wayfair',
  'Wells Fargo',
  'Workday',
  'Yelp',
  'Zillow',
  'Zoom',
  'Zscaler',
];
